### ISSUE TITLE
Reuse model from ModelDB

### ISSUE THREAD

**Issue by sunxiaoqing99** [ModelDBRepository/84589#1]
Good day,

I'm trying to reuse the model from ModelDB which due to the update of NEURON the code provided doesn't work any more :https://senselab.med.yale.edu/ModelDB/ShowModel.cshtml?model=84589&file=/eaps/cells/d151.hoc#tabs-1
I'm new at NEURON and I have tried to revise the code by myself but have failed many times, I really need some extra help from you guys, if anyone could give me some suggestions, that will help me a lot. Thanks in advance.

**Comment by sunxiaoqing99** [comment]
By the way, I'm using Win10 and by typing cmd:
`cd c:\eaps`
`c:\nrn59\bin\neuron.exe -dll mod\nrnmech.dll hoc/src/refs.hoc cells/d151.hoc hoc/src/file_util.hoc hoc/src/main.hoc`

These error messages showed up:
`Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018
See http://neuron.yale.edu/neuron/credits`
`loading membrane mechanisms from mod/nrnmech.dll
Additional mechanisms from files
cadif.mod cal.mod can.mod car.mod cat.mod hdend.mod hsoma.mod kadist.mod kahp.mod kaprox.mod kc.mod kd.mod kk.mod km.mod naf.mod nax.mod
LOADING refs
LOADING GEOMETRY FOR d151

-> Setting file roots...
SETTING WINDOWS FILE PATHS!

-> Updating trial number...
.\cells\d151_trial_num.txt
trial number 7

-> Making output directory...
COMMAND = mkdir output/d151_0007
The syntax of the command is incorrect.
RESULT = 1
COMMAND = mkdir output/d151_0007/nrn
The syntax of the command is incorrect.
RESULT = 1

-> Opening param & geometry files...

-> Loading param files...
LOADING CELL SPECIFIC MEMBRANE CONDUCTANCE DENSITIES...
param_dir = hoc/params
params file = hoc/params//d151_params.hoc
LOADING Cell Sepcific Params D151(A)!
C:\nrn\bin\nrniv.exe: output\d151_0007\nrn\d151_0007_param_names.txt :file is not open
in d151_params.hoc near line 34
gkk = 0.02
^
File[1].printf("%s
", "gkk")
write_param("gkk", "0.02")
define_param("gkk", "0.02")
xopen("d151_params.hoc")
and others
LOADING STANDARD MEMBRANE PARAMS FOR CELL TYPE:ca1pyr
LOADING STANDARD PARAMS for CA1 pyramidal cells...
C:\nrn\bin\nrniv.exe: output\d151_0007\nrn\d151_0007_param_names.txt :file is not open
in ca1pyr_standard_params.hoc near line 51
tstop = 25
^
File[1].printf("%s
", "tstop")
write_param("tstop", "25")
define_param("tstop", "25")
xopen("ca1pyr_sta...")
and others

-> Loading code files...
open cell util: hoc/src/cell_util.hoc
open current util: hoc/src/current_util.hoc
open template for mechanism description: hoc/src/mechdesc.hoc
C:\nrn\bin\nrniv.exe: String : a template cannot be redefined
in mechdesc.hoc near line 47
begintemplate String
^
xopen("mechdesc.hoc")
execute1("{xopen("me...")
load_file("hoc/src/me...")
load_code_files()
open membrane init file: hoc/src/membrane_init.hoc
C:\nrn\bin\nrniv.exe: MechDesc is not a template
in membrane_init.hoc near line 1182
tmp_ref = new MechDesc("naf", "na", "gbar")
^
xopen("membrane_i...")
execute1("{xopen("me...")
load_file("hoc/src/me...")
load_code_files()

-> Making section lists...
Making make_apical_lists...
C:\nrn\bin\nrniv.exe: undefined variable trunk_min_diam
in membrane_init.hoc near line 148
make_lists()
^
make_apical_lists()
make_lists()`

**Comment by sunxiaoqing99** [comment]
This answer was given by ramcdougal. Sorry that I'm new at Github and I didn't know how to move my topic here, instead, I copied and paste. 

The first error that runs into is the

COMMAND = mkdir output/d151_0007
Syntax error. 
Note that attempting to do mkdir output/d151_0007 in Windows 10 will give you a syntax error (although, curiously, on my system it says The syntax of the command is incorrect.)

To fix this to use the Windows-correct \, change line 161 of https://senselab.med.yale.edu/ModelDB/showmodel.cshtml?model=84589&file=/eaps/hoc/src/file_util.hoc#tabs-2 from

loadfile_mkdir_path_sep = "/"
to

loadfile_mkdir_path_sep = "\\"
(Yes, the backslash needs to be given twice; this is because a backslash has special meaning in strings in many programming languages, including HOC.)

Consider moving this discussion to the issues page for that particular model in ModelDB: https://github.com/modeldbrepository/84589/issues

**Comment by ramcdougal** [comment]
Did that help?

Note that it should say

    loadfile_mkdir_path_sep = "\\"

with two backslashes.

**Comment by sunxiaoqing99** [comment]
Thank you so much for your patient reply!
I tried your method but I still got error messages:
`loading membrane mechanisms from mod/nrnmech.dll
Additional mechanisms from files
cadif.mod cal.mod can.mod car.mod cat.mod hdend.mod hsoma.mod kadist.mod kahp.mod kaprox.mod kc.mod kd.mod kk.mod km.mod naf.mod nax.mod
LOADING GEOMETRY FOR d151

-> Setting file roots...
SETTING WINDOWS FILE PATHS!

-> Updating trial number...
.\cells\d151_trial_num.txt
trial number 3

-> Making output directory...
COMMAND = mkdir output/d151_0003
The syntax of the command is incorrect.
RESULT = 1
COMMAND = mkdir output/d151_0003/nrn
The syntax of the command is incorrect.
RESULT = 1

-> Opening param & geometry files...

-> Loading param files...
LOADING CELL SPECIFIC MEMBRANE CONDUCTANCE DENSITIES...
param_dir = hoc/params
params file = hoc/params//d151_params.hoc
LOADING Cell Sepcific Params D151(A)!
C:\nrn\bin\nrniv.exe: output\d151_0003\nrn\d151_0003_param_names.txt :file is not open
in d151_params.hoc near line 34
gkk = 0.02
^
File[1].printf("%s
", "gkk")
write_param("gkk", "0.02")
define_param("gkk", "0.02")
xopen("d151_params.hoc")
and others
LOADING STANDARD MEMBRANE PARAMS FOR CELL TYPE:ca1pyr
LOADING STANDARD PARAMS for CA1 pyramidal cells...
C:\nrn\bin\nrniv.exe: output\d151_0003\nrn\d151_0003_param_names.txt :file is not open
in ca1pyr_standard_params.hoc near line 51
tstop = 25
^
File[1].printf("%s
", "tstop")
write_param("tstop", "25")
define_param("tstop", "25")
xopen("ca1pyr_sta...")
and others

-> Loading code files...
open cell util: hoc/src/cell_util.hoc
open current util: hoc/src/current_util.hoc
open template for mechanism description: hoc/src/mechdesc.hoc
C:\nrn\bin\nrniv.exe: String : a template cannot be redefined
in mechdesc.hoc near line 47
begintemplate String
^
xopen("mechdesc.hoc")
execute1("{xopen("me...")
load_file("hoc/src/me...")
load_code_files()
open membrane init file: hoc/src/membrane_init.hoc
C:\nrn\bin\nrniv.exe: MechDesc is not a template
in membrane_init.hoc near line 1182
tmp_ref = new MechDesc("naf", "na", "gbar")
^
xopen("membrane_i...")
execute1("{xopen("me...")
load_file("hoc/src/me...")
load_code_files()

-> Making section lists...
Making make_apical_lists...
C:\nrn\bin\nrniv.exe: undefined variable trunk_min_diam
in membrane_init.hoc near line 148
make_lists()
^
make_apical_lists()
make_lists()`

(although, curiously, on my system it says The syntax of the command is incorrect.)
This is because the language of my Win10 is Chinese, so I was trying to translate by myself which seemed to be not that correct.

I didn't know how to move my issue to the website you gave, so I just copied and pasted with your name on the top of the reply, hope that wouldn't bother you.

I was thinking that if I could use the old version of NEURON to run this legacy code (NEURON 5.9), but I didn't know which part of the package should I use:
https://neuron.yale.edu/ftp/neuron/versions/v5.9/

Thanks again for your reply! I really appreciated that!

**Comment by tommorse** [comment]
Please try this new updated version which includes a mosinit.hoc file.  After you compile the mod files in mswin put the nrnmech.dll in the same folder as the mosinit.hoc and double click the mosinit.hoc in a file explorer. Let us know if it works for you.

**Comment by sunxiaoqing99** [comment]
The updated version works! Thanks a lot!

**Comment by tommorse** [comment]
Your very welcome!  Thanks for bringing this issue to our attention! As a final step I edited the documentation (readme file and docs/index) and made sure empty folders were retained, to complement this recent upgrade.
